import { first, second, third, fourth,fifth , sixth, seventh } from "./src/assets/keys";
// fifth key || there is a sound error

export const keySound = {
  q: first,
  w: second,
  e: third,
  r: fourth,
  t: seventh,
  y: sixth,
  u: fourth,
  i: second,
  o: sixth,
  p: seventh,
  "{": seventh,
  "}": second,
  "|": fourth,
  "enter": second,
  "shift": sixth,
  "tab": sixth,
  "ctrl": fourth,
  a: fourth,
  s: first,
  d: second,
  f: seventh,
  g: sixth,
  h: sixth,
  j: fourth,
  k: first,
  l: second,
  z: sixth,
  x: third,
  c: seventh,
  v: third,
  b: seventh,
  n: second,
  m: sixth,
};